### ISSUE TITLE
health check failing with an exception on a recent PR

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/ecosystem#125]
From https://github.com/dart-lang/ecosystem/actions/runs/5433464106/jobs/9881149515?pr=124 we see:

```
...
Collecting packages without changed changelogs:
Done, found 2 packages.
Collecting files without license headers in those packages:
Done, found 0 packages with a need for a changelog.
Unhandled exception:
Bad state: No element
#0      Iterable.reduce (dart:core/iterable.dart:[37](https://github.com/dart-lang/ecosystem/actions/runs/5433464106/jobs/9881149515?pr=124#step:8:38)4:7)
#1      Health.coverageCheck (package:firehose/src/health/health.dart:151:12)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#3      Health.healthCheck (package:firehose/src/health/health.dart:68:9)
<asynchronous suspension>
#4      main (file:///home/runner/work/ecosystem/ecosystem/current_repo/pkgs/firehose/bin/health.dart:20:3)
<asynchronous suspension>
```

cc @mosuem

**Comment by devoncarew** [comment]
(this is also affecting https://github.com/dart-lang/ecosystem/pull/122)
